### ISSUE TITLE
Can't log time due to faulty regEx

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/time-tracker#87]
The entered time is always invalid. Seems to be caused by a faulty regex:

`Pattern attribute value ^\d{4}\-\d{2}\-\d{2} is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^\d{4}\-\d{2}\-\d{2}/: Invalid escape`

Maybe new chrome version?! I have version 53.

Found this: https://productforums.google.com/forum/#!topic/chrome/c5wFchiOQUU

I would look at this myself, but don't know how to set up the dev env for the time tracker.

<a href="https://timer.scm.io/repos/537238621a000061003c4a1e/issues/87/create?referer=github" target="_blank">Log Time</a>

**Comment by hotzenklotz** [comment]
Same here. It seems like there are some changes with the `pattern` attribute and ES6. Some characters don't need escaping anymore.

```
remove slash before dash (-) for fix
old ^\s*\-?\s*(?:(\d+)\s*d)?\s*(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*$
new ^\s*-?\s*(?:(\d+)\s*d)?\s*(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*$
```

**Comment by hotzenklotz** [comment]
Fixed with commit 426f6540213664c420f3de94301b6d77ed2b984a

**Comment by daniel-wer** [comment]
The deployment doesn't seem to have worked. I'm still having the same issue.

**Comment by normanrz** [comment]
Yeah. There's no auto-deployment yet ;-)

**Comment by normanrz** [comment]
Just deployed.
